#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-2 --mode 1920x1080 --rate 144.00 &
picom &
feh --bg-fill --no-fehbg ~/Pictures/wallpapers/0310.png &


# Workspaces #
bspc monitor DP-2 -d I II III IV V 

# Extra config stuff #
bspc config border_width         4
bspc config window_gap          28
bspc config split_ratio          0.6
bspc config focus_follows_pointer true

# Colors #
bspc config normal_border_color "#8ec07c" 
bspc config focused_border_color "#75d588" 
bspc config presel_feedback_color "#98971a" 

# Rules #
bspc rule -a discord desktop="^2" follow=on
bspc rule -a firefox desktop="^1" follow=on
bspc rule -a lunarclient desktop="^5" follow=on


$HOME/.config/polybar/launch.sh
