#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-2 --mode 1920x1080 --rate 144.00 &
picom &
feh --bg-fill --no-fehbg ~/Pictures/wallpapers/0306.jpg &
$HOME/.config/polybar/launch.sh


# Workspaces
bspc monitor -d I II III IV V 

# Extra config stuff
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.6

# Rules
bspc rule -a firefox desktop="^1" follow=on
